import fs from 'node:fs';
import puppeteer from 'puppeteer';
export const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
export const box=(title,text)=>`<div class="box"><h3>${title}</h3><p>${text}</p></div>`;
export const lines=(labels)=>labels.map(t=>`<div class="field"><b>${t}</b><div class="ruled"></div></div>`).join('');
export const table=(headers,count)=>`<table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${Array.from({length:count},()=>`<tr>${headers.map(()=>'<td>&nbsp;</td>').join('')}</tr>`).join('')}</tbody></table>`;
export async function pdf(filename,pages){
 const font=name=>'data:font/ttf;base64,'+fs.readFileSync('pinterest/fonts/'+name).toString('base64');
 const css=`@font-face{font-family:DM;src:url('${font('DMSans.ttf')}')}@font-face{font-family:Serif;src:url('${font('DMSerifDisplay-Regular.ttf')}')}*{box-sizing:border-box}body{margin:0;color:#3D2C2E;font-family:DM,sans-serif;background:#FDF8F4;font-size:12pt;line-height:1.55}.page{width:210mm;height:297mm;position:relative;overflow:hidden;padding:22mm 19mm 23mm;break-after:page}.page:last-child{break-after:auto}.brand{font-size:9pt;font-weight:700;letter-spacing:2px;color:#C4745A;border-bottom:1px solid #d8cfc6;padding-bottom:6mm;margin-bottom:9mm}h1,h2{font-family:Serif;font-weight:400;line-height:1.12}h1{font-size:38pt;margin:20mm 0 8mm}h2{font-size:29pt;margin:0 0 8mm}h3{font-size:13pt;margin:0 0 4mm;color:#735045}p{margin:0 0 6mm}.tag{display:inline-block;background:#8FAE8B;color:white;padding:2mm 4mm;border-radius:20mm;font-size:9pt}.box{background:white;border:1px solid #dfd5cc;border-radius:4mm;padding:6mm;margin:5mm 0}.field{margin:5mm 0}.ruled{height:20mm;background:repeating-linear-gradient(to bottom,transparent 0,transparent 6mm,#ded4cb 6.1mm,#ded4cb 6.3mm)}table{width:100%;border-collapse:collapse;margin-top:5mm;font-size:10pt}th{background:#8FAE8B;color:#fff;padding:3mm;text-align:left}td{border-bottom:1px solid #d9d0c7;height:12mm;padding:2mm}footer{position:absolute;bottom:10mm;left:19mm;right:19mm;border-top:1px solid #d8cfc6;padding-top:3mm;display:flex;justify-content:space-between;font-size:8pt;color:#806b68}.review{font-size:9pt;color:#9d452f;padding:3mm;background:#f1ded5;border-radius:3mm;margin:4mm 0}.wordgrid{display:grid;grid-template-columns:repeat(4,1fr);gap:3mm}.word{background:white;border-radius:4mm;padding:3mm;text-align:center;min-height:14mm}.word img{height:22mm;width:25mm;object-fit:contain;display:block;margin:0 auto 2mm}.coverart{height:62mm;border-radius:50% 50% 4mm 4mm;background:#e2eadd;padding:10mm;font-family:Serif;font-size:24pt;margin:10mm 0;display:flex;align-items:center;justify-content:center;text-align:center}.small{font-size:9pt}a{color:#a05238}`;
 const html=`<!doctype html><html lang="es"><head><meta charset="utf-8"><style>${css}</style></head><body>${pages.map((p,i)=>`<section class="page"><div class="brand">ESPACIO LENGUAJE · LOGOPEDIA / FONOAUDIOLOGÍA</div>${p}<footer><span>BORRADOR PRIVADO · PENDIENTE DE REVISIÓN</span><span>${i+1} / ${pages.length}</span></footer></section>`).join('')}</body></html>`;
 fs.mkdirSync(filename.split('/').slice(0,-1).join('/'),{recursive:true});fs.writeFileSync(filename.replace(/\.pdf$/,'.html'),html);
 const browser=await puppeteer.launch({headless:true});try{const page=await browser.newPage();await page.setContent(html,{waitUntil:'load'});await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));});const overflows=await page.evaluate(()=>[...document.querySelectorAll('.page')].map((p,i)=>({page:i+1,overflow:p.scrollHeight>p.clientHeight})));if(overflows.some(x=>x.overflow))throw Error(JSON.stringify(overflows));await page.pdf({path:filename,format:'A4',printBackground:true,preferCSSPageSize:true});console.log(filename+' · '+pages.length+' páginas');}finally{await browser.close();}
}
